apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-tls
  namespace: userspace
spec:
  secretName: nginx-tls
  duration: 670h
  renewBefore: 350h
  issuerRef:
    name: selfsigned-cluster
    kind: ClusterIssuer
  dnsNames:
  - nginx.userspace.svc.cluster.local
